### ISSUE TITLE
Duplicate key 'include'

### ISSUE THREAD

**Issue by edwdeapri** [EXSyst/php-twig#21]
Failed to load snippets from '/Users/pritchardFamily/.atom/packages/language-twig/snippets/PHP-twig.cson'
/Users/pritchardFamily/.atom/packages/language-twig/snippets/PHP-twig.cson: Duplicate key 'include'

Need to remove one of the 'include'.

**Comment by p-chan** [comment]
Hey guys.

I regret that it will not be updated soon :cry:
https://twitter.com/GuilhemN_/status/1001885619285626881

I made [language-twig-patch](https://atom.io/packages/language-twig-patch) package only to deal with this problem.
Please use it if you like.

**Comment by Abdillah** [comment]
Hello, good news, it has been fixed. You can upgrade to 1.6.4 release via the editor.
