### ISSUE TITLE
Duplicate key include

### ISSUE THREAD

**Issue by cahb52** [EXSyst/php-twig#22]
hi, i used php-twig in atom and allways on start up the program show the follow message:
Failed to load snippets from 'C:\Users\user.atom\packages\language-twig\snippets\PHP-twig.cson'
.atom\packages\language-twig\snippets\PHP-twig.cson: Duplicate key 'include'
can you help me to fix this?

**Comment by Abdillah** [comment]
Hello, it has been fixed and you can upgrade to 1.6.4 release via the editor.
