### ISSUE TITLE
Toggle Line Comments

### ISSUE THREAD

**Issue by carlcs** [EXSyst/php-twig#4]
It would be great if there was support for Twig comments with the "CMD + /" toggle line comments function, so that:

```twig
{% set comment = 'Not working yet!' %}
```
changes to:

```twig
{# set comment = 'Not working yet!' #}
```

**Comment by thamas** [comment]
It would be nice to be able to choose between Twig comment and HTML comment when using HTML Twig grammar. It is always HTML comment currently.

**Comment by Ener-Getick** [comment]
@thamas not sure that's possible, why would you need that ?

**Comment by carlcs** [comment]
@Ener-Getick I recently made the switch to the Craft-Twig package, which has some nice Craft CMS specific snippets. https://github.com/fruitstudios/Craft-Twig

Not sure if you improved the commenting behavior since I last checked, but it works perfectly using Craft-Twig. Though it might be interesting for you! Cheers
