### ISSUE TITLE
Are there differences in fork?

### ISSUE THREAD

**Issue by mediadoneright** [EXSyst/php-twig#5]
The readme says this is a fork of https://github.com/reesef/php-twig

confusing.  

Are there differences?  It would help if there were listed in the readme.

Why not work together on a single project?

**Comment by Ener-Getick** [comment]
There were more language supports in this package but it was merged in https://github.com/reesef/php-twig.
And I don't know if @reesef is still active. My last pull request was merged 1 month after.

**Comment by piotr-cz** [comment]
Please not that in the README.md file. It's super confusing to find the difference between these two packages without making a repo diff.
